<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.keenvil.parent</groupId>
  <artifactId>parent</artifactId>
  <version>3.0.4-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>parent</name>
  <description>Baseline Parent POM</description>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.5.RELEASE</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>11</java.version>
    <restassured.version>3.2.0</restassured.version>
    <gson.version>2.8.5</gson.version>
    <jackson-databind.version>2.9.7</jackson-databind.version>
    <twilio-sdk.version>7.42.0</twilio-sdk.version>
    <easymock.version>4.0.2</easymock.version>
    <mockito.version>2.23.0</mockito.version>
    <commons-lang3.version>3.9</commons-lang3.version>
    <commons-codec.version>1.6</commons-codec.version>
    <validation-api.version>2.0.1.Final</validation-api.version>
    <hibernate-validator.version>6.0.13.Final</hibernate-validator.version>
    <hikaricp.version>3.4.2</hikaricp.version>
    <liquibase.version>3.8.7</liquibase.version>
    <jjwt.version>0.9.1</jjwt.version>
    <spring.version>5.2.4.RELEASE</spring.version>
    <sentry.version>1.7.22</sentry.version>
    <kotlin.version>1.3.30</kotlin.version>
    <spring-cloud.version>Hoxton.SR2</spring-cloud.version>
    <aws.version>1.11.736</aws.version>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-core</artifactId>
        <version>${liquibase.version}</version>
      </dependency>

      <dependency>
        <groupId>com.zaxxer</groupId>
        <artifactId>HikariCP</artifactId>
        <version>${hikaricp.version}</version>
      </dependency>

      <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${jackson-databind.version}</version>
      </dependency>


      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk</artifactId>
        <version>${aws.version}</version>
      </dependency>

      <dependency>
        <groupId>com.twilio.sdk</groupId>
        <artifactId>twilio</artifactId>
        <version>${twilio-sdk.version}</version>
      </dependency>

      <dependency>
        <groupId>io.jsonwebtoken</groupId>
        <artifactId>jjwt</artifactId>
        <version>${jjwt.version}</version>
      </dependency>

      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

    </dependencies>
  </dependencyManagement>


  <dependencies>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>${spring.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-aspects</artifactId>
      <version>${spring.version}</version>
    </dependency>


    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zipkin</artifactId>
    </dependency>

    <!-- Commons Utilities -->
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
        <version>${commons-lang3.version}</version>
    </dependency>
    <dependency>
        <groupId>commons-codec</groupId>
        <artifactId>commons-codec</artifactId>
        <version>${commons-codec.version}</version>
    </dependency>

    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
      <version>${hibernate-validator.version}</version>
    </dependency>

    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
      <version>${validation-api.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jetty</artifactId>
    </dependency>

    <dependency>
      <groupId>com.fasterxml.jackson.module</groupId>
      <artifactId>jackson-module-kotlin</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
    </dependency>

    <!-- Testing -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.easymock</groupId>
      <artifactId>easymock</artifactId>
      <version>${easymock.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>${gson.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <version>${restassured.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.sentry</groupId>
      <artifactId>sentry-spring</artifactId>
      <version>${sentry.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.mockito/mockito-core -->
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>${mockito.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <profiles>
    <profile>
      <id>vulas</id>
      <activation>
        <property>
          <name>vulas</name>
        </property>
      </activation>
      <properties>
        <vulas.version>3.1.6</vulas.version>
        <vulas.shared.backend.serviceUrl>http://teamcity.int.myaws.io:8033/backend</vulas.shared.backend.serviceUrl>
        <vulas.core.space.token>362F2909685AC29B8576E9E23C9D0F5A</vulas.core.space.token>
        <vulas.core.appContext.group>${project.groupId}</vulas.core.appContext.group>
        <vulas.core.appContext.artifact>${project.artifactId}</vulas.core.appContext.artifact>
        <vulas.core.appContext.version>${project.version}</vulas.core.appContext.version>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>com.sap.research.security.vulas</groupId>
            <artifactId>plugin-maven</artifactId>
            <version>${vulas.version}</version>
            <configuration>
              <layeredConfiguration>
                <vulas.shared.backend.serviceUrl>${vulas.shared.backend.serviceUrl}</vulas.shared.backend.serviceUrl>
                <vulas.core.space.token>${vulas.core.space.token}</vulas.core.space.token>

                <vulas.core.appContext.group>${vulas.core.appContext.group}</vulas.core.appContext.group>
                <vulas.core.appContext.artifact>${vulas.core.appContext.artifact}</vulas.core.appContext.artifact>
                <vulas.core.appContext.version>${vulas.core.appContext.version}</vulas.core.appContext.version>

                <vulas.shared.tmpDir>${project.build.directory}/vulas/tmp</vulas.shared.tmpDir>
                <vulas.core.uploadDir>${project.build.directory}/vulas/upload</vulas.core.uploadDir>
                <vulas.core.app.sourceDir>${project.build.directory}/classes,${project.basedir}/src/main/java,${project.basedir}/src/main/python</vulas.core.app.sourceDir>

                <!-- vulas:instr : Instruments JAR/WAR files found in source dir,
                    and writes to target dir. Files in include dir are put into /WEB-INF/lib
                    of output WARs. Files in lib dir are part of the class path when instrumenting. -->
                <vulas.core.instr.sourceDir>${project.build.directory}</vulas.core.instr.sourceDir>
                <vulas.core.instr.targetDir>${project.build.directory}/vulas/target</vulas.core.instr.targetDir>
                <vulas.core.instr.includeDir>${project.build.directory}/vulas/include</vulas.core.instr.includeDir>
                <vulas.core.instr.libDir>${project.build.directory}/vulas/lib</vulas.core.instr.libDir>
                <vulas.core.instr.writeCode>false</vulas.core.instr.writeCode>
                <vulas.core.instr.instrumentorsChoosen>com.sap.psr.vulas.monitor.trace.SingleTraceInstrumentor</vulas.core.instr.instrumentorsChoosen>
                <vulas.core.instr.searchRecursive>false</vulas.core.instr.searchRecursive>
                <vulas.core.monitor.periodicUpload.enabled>false</vulas.core.monitor.periodicUpload.enabled>
                <vulas.core.instr.maxStacktraces>10</vulas.core.instr.maxStacktraces>

                <!-- vulas:a2c/t2c : Performs static call graph analysis -->
                <vulas.reach.wala.callgraph.reflection>NO_FLOW_TO_CASTS_NO_METHOD_INVOKE</vulas.reach.wala.callgraph.reflection>
                <vulas.reach.timeout>60</vulas.reach.timeout>

                <!-- vulas:report -->
                <vulas.report.exceptionExcludeBugs></vulas.report.exceptionExcludeBugs>
                <vulas.report.reportDir>${project.build.directory}/vulas/report</vulas.report.reportDir>
              </layeredConfiguration>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>2.17</version>
        <configuration>
          <configLocation>https://raw.githubusercontent.com/keenvil/checkstyle/master/checkstyle.xml</configLocation>
          <encoding>UTF-8</encoding>
          <consoleOutput>true</consoleOutput>
          <failOnViolation>false</failOnViolation>
          <failsOnError>false</failsOnError>
          <linkXRef>false</linkXRef>
        </configuration>
        <executions>
          <execution>
           <id>validate</id>
           <phase>validate</phase>
           <goals>
             <goal>check</goal>
           </goals>
         </execution>
       </executions>
       <dependencies>
        <dependency>
          <groupId>com.puppycrawl.tools</groupId>
          <artifactId>checkstyle</artifactId>
          <version>6.19</version>
        </dependency>
      </dependencies>
    </plugin>
      <plugin>
        <artifactId>kotlin-maven-plugin</artifactId>
        <groupId>org.jetbrains.kotlin</groupId>
        <version>${kotlin.version}</version>
        <executions>
          <execution>
            <id>compile</id>
            <goals> <goal>compile</goal> </goals>
            <configuration>
              <sourceDirs>
                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                <sourceDir>${project.basedir}/src/main/java</sourceDir>
              </sourceDirs>
            </configuration>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals> <goal>test-compile</goal> </goals>
            <configuration>
              <sourceDirs>
                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                <sourceDir>${project.basedir}/src/test/java</sourceDir>
              </sourceDirs>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.10.1</version>
        <executions>
          <!-- Replacing default-compile as it is treated specially by maven -->
          <execution>
            <id>default-compile</id>
            <phase>none</phase>
          </execution>
          <!-- Replacing default-testCompile as it is treated specially by maven -->
          <execution>
            <id>default-testCompile</id>
            <phase>none</phase>
          </execution>
          <execution>
            <id>java-compile</id>
            <phase>compile</phase>
            <goals> <goal>compile</goal> </goals>
          </execution>
          <execution>
            <id>java-test-compile</id>
            <phase>test-compile</phase>
            <goals> <goal>testCompile</goal> </goals>
          </execution>
        </executions>
      </plugin>
    <plugin>
      <groupId>org.jacoco</groupId>
      <artifactId>jacoco-maven-plugin</artifactId>
      <version>0.8.7</version>
      <executions>
        <execution>
          <id>default-prepare-agent</id>
          <goals>
            <goal>prepare-agent</goal>
          </goals>
        </execution>
        <execution>
          <id>default-prepare-agent-integration</id>
          <goals>
            <goal>prepare-agent-integration</goal>
          </goals>
        </execution>
        <execution>
          <id>default-report</id>
          <goals>
            <goal>report</goal>
          </goals>
        </execution>
        <execution>
          <id>default-report-integration</id>
          <goals>
            <goal>report-integration</goal>
          </goals>
        </execution>
        <execution>
          <id>default-check</id>
          <goals>
            <goal>check</goal>
          </goals>
          <configuration>
            <rules>
              <rule>
                <element>CLASS</element>
                  <excludes>
                    <exclude>*Application</exclude>
                    <exclude>*Dto</exclude>
                    <exclude>*Type</exclude>
                    <exclude>*ExceptionHandler</exclude>
                    <exclude>*Response</exclude>
                    <exclude>*Configuration</exclude>
                    <exclude>*Config</exclude>
                    <exclude>*ControllerAdvice</exclude>
                    <exclude>*Properties</exclude>
                  </excludes>
                <limits>
                  <limit>
                    <counter>COMPLEXITY</counter>
                    <value>COVEREDRATIO</value>
                    <minimum>0.60</minimum>
                  </limit>
                  <limit>
                    <counter>CLASS</counter>
                    <value>MISSEDCOUNT</value>
                    <maximum>0</maximum>
                  </limit>
                   <limit>
                    <counter>CLASS</counter>
                    <value>COVEREDRATIO</value>
                    <minimum>0.75</minimum>
                  </limit>
                </limits>
              </rule>
            </rules>
          </configuration>
        </execution>
      </executions>
    </plugin>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>3.0.0-M5</version>
      <configuration>
        <excludes>
          <exclude>**/*IntegrationTest.java</exclude>
        </excludes>
      </configuration>
    </plugin>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-failsafe-plugin</artifactId>
      <version>3.0.0-M5</version>
      <configuration>
        <includes>
          <include>**/*IntegrationTest.java</include>
        </includes>
      </configuration>
      <executions>
        <execution>
          <id>default-integration-test</id>
          <goals>
            <goal>verify</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>

<distributionManagement>
  <snapshotRepository>
    <id>nexus-snapshots</id>
    <url>http://nexus.int.myaws.io:8081/repository/maven-snapshots/</url>
  </snapshotRepository>
</distributionManagement>

<repositories>
  <repository>
    <id>myco</id>
    <url>http://nexus.int.myaws.io:8081/repository/maven-public/</url>
    <releases>
      <enabled>true</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>

  <repository>
    <id>jcenter-snapshots</id>
    <name>jcenter</name>
    <url>https://jcenter.bintray.com/</url>
  </repository>
</repositories>

<reporting>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-checkstyle-plugin</artifactId>
      <version>3.1.2</version>
      <reportSets>
        <reportSet>
          <reports>
            <report>checkstyle</report>
          </reports>
        </reportSet>
      </reportSets>
    </plugin>
  </plugins>
</reporting>

</project>
